cvm-version: 0.7.5
cpus: 4
memory: 16384

containers:
  - name: "container"
    image: "ghcr.io/tinfoilsh/system-prompt-injector@sha256:f801ee4f09959c6bf83c01c77476ddf80efd489414082e577ae31e812dfc7a2b" # v0.0.15
    env:
      - TINFOIL_INFERENCE_URL: "https://inference.tinfoil.sh"
    secrets:
      - SYSTEM_PROMPT_TEMPLATE

shim:
  upstream-port: 8080
  paths:
    - /healthz
    - /v1/chat/completions
